version: '3'
services:
  app:
    container_name: app
    build: .
    tty: true
    # environment:
    #   APP_MODE: local
    #   DB_PASSWORD: localpass
    volumes:
      - './src:/go/src/sample-app'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5430:5432'
    environment:
      POSTGRES_DB: restapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    restart: always
    tty: true

  proxy:
    container_name: proxy
    build: ./nginx
    ports:
      - '8081:80'
    depends_on:
      - app
